apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-be-api
  labels:
    app: my-be-api
  annotations:
    dev.okteto.com/auto-ingress: "true"    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-api
  template:
    metadata:
      labels:
        app: be-api
    spec:
      containers:
      - name: be-api-container
        image: guts2501/be_api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
